### ISSUE TITLE
Cannot call self-signed BAM or use HTTP

### ISSUE THREAD

**Issue by gradinDotCom** [umich-vci/terraform-provider-bluecat#1]
The BAM endpoint configuration appears to be locked down. Is there a way for me to pass a field to ignore certificate errors?

**Comment by adarobin** [comment]
Hi @gradinDotCom.  It's been a while since I've dug into the client code.  The client was mostly generated from the upstream WSDL spec.  Something would need to be added to https://github.com/umich-vci/gobam first before we could add an option to the provider.

If I am able to throw something together would you be able to test it?

**Comment by gradinDotCom** [comment]
I passed a bool into the gobam function to make the connection. There's a case on there for insecure client, which looks to have worked! I wanted to look into block creation too, but first I'm concerned about using hints to find networks or blocks in the data resource. I don't know anything about GoLang, but I'll see what I can do to expose some different methods here. If I can get it working, I'll push it up.

**Comment by adarobin** [comment]
@gradinDotCom I updated the function yesterday, but I didn’t want to go too far down that road since I don’t have a way of testing. I should be able to throw something together for this for tomorrow.

**Comment by gradinDotCom** [comment]
I can test today. I am trying to integrate this into an active pattern I maintain.

**Comment by adarobin** [comment]
@gradinDotCom I just pushed some code that should let you skip SSL certificate checks.  There is a new provider option called "ssl_verify" that defaults to `true`.  I have attached a copy of this built for Linux x86_64. If you need a different arch, just let me know.

If you can confirm this works with a self-signed certificate, I can make a 0.2.0 release and push it to the registry.


[terraform-provider-bluecat.zip](https://github.com/umich-vci/terraform-provider-bluecat/files/5452436/terraform-provider-bluecat.zip)

**Comment by gradinDotCom** [comment]
I compiled a release for Windows and included the ssl_verify = false option in my provider block. Worked perfectly. Previously, I had done the same thing, but compiled a different call to your gobam module which worked the same way. This is definitely better than compiling a different version ;).
